// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the exporter/s3 component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("s3")
	ScopeName = "github.com/grepplabs/jetstream-collector/exporter/s3exporter"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
