// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the processor/partitionbyattrs component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("partitionbyattrs")
	ScopeName = "github.com/grepplabs/jetstream-collector/processor/partitionbyattrsprocessor"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
