extensions:
  basicauth/victoriametrics:
    client_auth:
      username: ${env:VICTORIAMETRICS_USERNAME}
      password: ${env:VICTORIAMETRICS_PASSWORD}

exporters:
  otlphttp/victoriametrics:
    metrics_endpoint: http://localhost:8080
    compression: gzip
    encoding: proto
    auth:
      authenticator: basicauth/victoriametrics

    timeout: 15s

    sending_queue:
      enabled: false

    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 3s
      max_elapsed_time: 15s

receivers:
  jetstream/victoriametrics-metrics:
    url: nats://127.0.0.1:30422
    stream: METRICS_INPUT
    subject: metrics.input
    consumer_name: victoriametrics-metrics
    workers: 10

service:
  extensions:
    - basicauth/victoriametrics

  pipelines:
    metrics/victoriametrics:
      receivers:
        - jetstream/victoriametrics-metrics
      exporters:
        - otlphttp/victoriametrics

  telemetry:
    resource:
      service.name: jetstream-collector
      service.version: "0.0.0-test"
    logs:
      level: debug
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888
