apiVersion: v1
kind: Secret
metadata:
  name: seaweed-secret
  namespace: seaweedfs-cluster
type: Opaque
stringData:
  seaweedfs_s3_config.json: |
    {
      "identities": [
        {
          "name": "admin",
          "actions": [
            "Admin"
          ],
          "credentials": [
            {
              "accessKey": "admin",
              "secretKey": "admin123"
            }
          ]
        }
      ]
    }
