---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: tenant
  namespace: collectors
spec:
  mode: deployment
  replicas: 1

  image: local/jetstream-collector:local
  # imagePullPolicy: Never

  ports:
    - name: otlp-grpc
      port: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      protocol: TCP

  config:
    receivers:
      otlp/tenant:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            include_metadata: true
          http:
            endpoint: 0.0.0.0:4318
            include_metadata: true

    exporters:
      jetstream/logs-tenant:
        url: nats://nats.nats.svc.cluster.local:4222
        subject_pattern: logs.tenant.$${header:X-Tenant-ID}
        include_subject: true
        compression: gzip
        content_type: proto
        msg_id: true

      jetstream/metrics-tenant:
        url: nats://nats.nats.svc.cluster.local:4222
        subject_pattern: metrics.tenant.$${header:X-Tenant-ID}
        include_subject: true
        compression: gzip
        content_type: proto
        msg_id: true

    service:
      pipelines:
        logs/tenant:
          receivers:
            - otlp/tenant
          exporters:
            - jetstream/logs-tenant

        metrics/tenant:
          receivers:
            - otlp/tenant
          exporters:
            - jetstream/metrics-tenant

      telemetry:
        logs:
          level: debug
        metrics:
          level: detailed
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: 0.0.0.0
                    port: 8888
