---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: victoriametrics-metrics
  namespace: collectors
spec:
  streamName: METRICS_INPUT
  durableName: victoriametrics-metrics
  filterSubject: metrics.input
  ackPolicy: explicit
  deliverPolicy: new
  replayPolicy: instant
  ackWait: 120s
  maxAckPending: 200
  maxDeliver: -1
