---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: splitter-resource-logs
  namespace: collectors
spec:
  streamName: LOGS_INPUT
  durableName: splitter-resource-logs
  filterSubject: logs.input
  ackPolicy: explicit
  deliverPolicy: new
  replayPolicy: instant
  ackWait: 120s
  maxAckPending: 200
  maxDeliver: -1
