// Code generated by mdatagen. DO NOT EDIT.
package metadata

import "go.opentelemetry.io/collector/component"

var (
	Type      = component.MustNewType("clientmetadataselector")
	ScopeName = "github.com/grepplabs/jetstream-collector/processor/clientmetadataselector"
)

const (
	LogsStability     = component.StabilityLevelAlpha
	MetricsStability  = component.StabilityLevelAlpha
	TracesStability   = component.StabilityLevelAlpha
	ProfilesStability = component.StabilityLevelAlpha
)
