// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/jetstream component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("jetstream")
	ScopeName = "github.com/grepplabs/jetstream-collector/receiver/jetstreamreceiver"
)

const (
	LogsStability     = component.StabilityLevelAlpha
	MetricsStability  = component.StabilityLevelAlpha
	TracesStability   = component.StabilityLevelAlpha
	ProfilesStability = component.StabilityLevelAlpha
)
