// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the processor/clientmetadata component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("clientmetadata")
	ScopeName = "github.com/grepplabs/jetstream-collector/processor/clientmetadataprocessor"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
