apiVersion: seaweed.seaweedfs.com/v1
kind: Bucket
metadata:
  name: quickwit
  namespace: quickwit
spec:
  clusterRef:
    name: seaweed
    namespace: seaweedfs-cluster
  reclaimPolicy: Delete

---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Identity
metadata:
  name: quickwit
  namespace: quickwit
spec:
  seaweedRef:
    name: seaweed
    namespace: seaweedfs-cluster
  name: quickwit
  reclaimPolicy: Delete

---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: quickwit
  namespace: quickwit
spec:
  seaweedRef:
    name: seaweed
    namespace: seaweedfs-cluster
  identityRef:
    name: quickwit
  secretRef:
    name: quickwit-s3-credentials
  reclaimPolicy: Delete

---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Policy
metadata:
  name: quickwit-read-write
  namespace: quickwit
spec:
  seaweedRef:
    name: seaweed
    namespace: seaweedfs-cluster
  reclaimPolicy: Delete
  statements:
    - effect: Allow
      actions:
        - s3:ListBucket
        - s3:GetBucketLocation
        - s3:ListBucketMultipartUploads
      resources:
        - quickwit

    - effect: Allow
      actions:
        - s3:GetObject
        - s3:GetObjectVersion
        - s3:PutObject
        - s3:DeleteObject
        - s3:DeleteObjectVersion
        - s3:GetObjectTagging
        - s3:PutObjectTagging
        - s3:DeleteObjectTagging
        - s3:AbortMultipartUpload
        - s3:ListMultipartUploadParts
      resources:
        - quickwit/*

---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3PolicyBinding
metadata:
  name: quickwit
  namespace: quickwit
spec:
  seaweedRef:
    name: seaweed
    namespace: seaweedfs-cluster
  policyRef:
    name: quickwit-read-write
  subjects:
    - kind: S3Identity
      name: quickwit
  reclaimPolicy: Delete
